# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint and Prettier

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '25 9 * * 5'

jobs:
  eslint-prettier:
    name: Run ESLint and Prettier scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint and Prettier
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0
          npm install prettier eslint-plugin-prettier eslint-config-prettier --save-dev

      - name: Run Prettier auto-format
        run: |
          npx prettier --check "**/*.{js,jsx,ts,tsx,json,md}"
        continue-on-error: True  # 如果不希望在有格式化问题时失败，可以设置为 true，但最好保持为 false 确保格式问题修复

      - name: Run ESLint with Prettier integrated
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint . \
          --config .eslintrc.json \
          --ext .js,.jsx,.ts,.tsx \
          --format @microsoft/eslint-formatter-sarif \
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

      - name: Send ESLint and Prettier notification to Discord
        if: always()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          DEPLOY_URL: ${{ secrets.VERCEL_PROJECT_DOMAIN }}
        run: |
          MESSAGE="📝 **ESLint and Prettier Check Completed**\n\n"
          MESSAGE+="**Repository**: ${{ github.repository }}\n"
          MESSAGE+="**Commit**: \`${{ github.sha }}\`\n"
          MESSAGE+="**Branch**: ${{ github.ref_name }}\n\n"
          MESSAGE+="✅ **Build Succeeded**: Branch '${{ github.ref_name }}'\n"
          MESSAGE+="**Commit**: \`${{ github.sha }}\`\n"
          MESSAGE+="**Author**: ${{ github.actor }}\n\n"
          MESSAGE+="**Deployed to Vercel**: 🌐 ${{ secrets.VERCEL_PROJECT_DOMAIN }}\n\n"
          MESSAGE+="🔗 **View CI/CD Logs**: [GitHub Actions Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\n"
          
          # Sending message to Discord
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$MESSAGE\"}" $DISCORD_WEBHOOK_URL

