# .github/workflows/ci.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout 代码
      - uses: actions/checkout@v3

      # 设置 Node.js 版本
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.0"

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 构建项目
      - name: Build project
        run: npm run build

      # 发送通知到 Discord 和 API
      - name: Send failure notification on error
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          MESSAGE="🚨 Build failed on branch '${{ github.ref }}'. Please check the logs for details."
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$MESSAGE\"}" $DISCORD_WEBHOOK_URL
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: $API_KEY" \
            -d "{\"stage\": \"Build\", \"status\": \"Failure\", \"logs\": \"$MESSAGE\"}" \
            https://itmd-536-group3-project.vercel.app/api/status
        
      - name: Send success notification on error        
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          MESSAGE="✅ Build succeeded on branch '${{ github.ref }}'."
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$MESSAGE\"}" $DISCORD_WEBHOOK_URL
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: $API_KEY" \
            -d "{\"stage\": \"Build\", \"status\": \"Failure\", \"logs\": \"$MESSAGE\"}" \
            https://itmd-536-group3-project.vercel.app/api/status