name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.0"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm run test

      # Build the project
      - name: Build project
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: npm run build

      # Notify Discord and API on build failure
      - name: Send failure notification on error
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          MESSAGE="🚨 **Build Failed**: Branch '${{ github.ref_name }}'\n\n"
          MESSAGE+="**Commit**: \`${{ github.sha }}\`\n"
          MESSAGE+="**Author**: ${{ github.actor }}\n\n"
          MESSAGE+="📄 **Check logs for details**: [GitHub Actions Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          
          # Send to Discord
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$MESSAGE\"}" $DISCORD_WEBHOOK_URL
          # Send to API
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: $API_KEY" \
            -d "{\"stage\": \"Build\", \"status\": \"Failure\", \"logs\": \"$MESSAGE\"}" \
            https://itmd-536-group3-project.vercel.app/api/status
        
      # Notify Discord and API on build success
      - name: Send success notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          MESSAGE="✅ **Build Succeeded**: Branch '${{ github.ref_name }}'\n\n"
          MESSAGE+="**Commit**: \`${{ github.sha }}\`\n"
          MESSAGE+="**Author**: ${{ github.actor }}\n\n"
          MESSAGE+="🌐 **Deployed to Vercel**: [${{ secrets.VERCEL_PROJECT_DOMAIN }}](${ secrets.VERCEL_PROJECT_DOMAIN })\n"
          MESSAGE+="🔗 **View CI/CD Logs**: [GitHub Actions Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          
          # Send to Discord
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$MESSAGE\"}" $DISCORD_WEBHOOK_URL
          # Send to API
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: $API_KEY" \
            -d "{\"stage\": \"Build\", \"status\": \"Success\", \"logs\": \"$MESSAGE\"}" \
            https://itmd-536-group3-project.vercel.app/api/status
